<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Hello</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../sdks/dotnet/src/Codefrak.Hitlp/Codefrak.Hitlp.csproj" />
  </ItemGroup>

</Project>
